name: untask
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  freezed_annotation: ^2.4.1
  go_router: ^14.1.2
  json_annotation: ^4.9.0
  nanoid: ^1.0.0
  path_provider: ^2.0.15

dev_dependencies:
  build_runner: ^2.4.10
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.3
  json_serializable: ^6.8.0

dependency_overrides:
  meta: ^1.7.0
  intl: ^0.19.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
